### ISSUE TITLE
[Feature] Add `JuliaWin.ini` or `JuliaWin.bat` for User Configuration for Launcher

### ISSUE THREAD

**Issue by RoyiAvital** [heetbeet/juliawin#64]
Add the functionality of `winpython.ini` file which allows defining _System Variables_ / _Environment Variables_ to be applied to all launchers.

**Comment by heetbeet** [comment]
From v1.8.1-0 if the file `userdata\startup.cmd` or `userdata\startup.bat` exists, it will be automatically executed at the end of the `activate-juliawin-environment` routine (to grant the opportunity to change/overwrite those variables as well).

**Comment by RoyiAvital** [comment]
Could we write some documentation? What `activate-julia-environment` defines?

**Comment by heetbeet** [comment]
juliawin_home = _absolute path of base directory_
juliawin_bin = %juliawin_home%\bin
juliawin_packages = %juliawin_home%\packages
juliawin_userdata = %juliawin_home%\userdata
juliawin_sh = juliawin_packages%\git\bin\sh.exe _or_ %PROGRAMFILES<(x86)>%\Git\bin\sh.exe _or sh.exe from `where git`_
juliawin_activated = 1

JULIA_DEPOT_PATH = %juliawin_userdata%\\.julia
CONDA_JL_HOME = %juliawin_packages%\conda
PYTHON = _empty by use of %JULIA_DEPOT_PATH%\config\startup.jl, since bat cannot set empty variables_

The following directories are added to PATH
- %juliawin_packages%\julia\bin
- %juliawin_packages%\curl\bin
- %juliawin_packages%\vscode

**Comment by heetbeet** [comment]
Above is a summary of what the activate script sets, I'm not sure where to properly document it. PRs are welcome

**Comment by RoyiAvital** [comment]
I started with the Wiki: https://github.com/heetbeet/juliawin/wiki/Setting-System-Variables-(Environment-Variables)
