### ISSUE TITLE
Add Git dependency to readme.md

### ISSUE THREAD

**Issue by kuelshammer** [heetbeet/juliawin#8]

**Comment by heetbeet** [comment]
Just to clarify @kuelshammer , did you find the pipeline to break somewhere if git isn't installed? And do you know where exactly in the pipeline?

**Comment by kuelshammer** [comment]
@heetbeet: During install with .bat-file I got messages that git is not in PATH and those lines were red. I delete that folder, will repeat the process later today.

**Comment by heetbeet** [comment]
@kuelshammer thanks, i quickly tried to reproduce the error by uninstalling my git, making sure no git is in PATH and running the .bat file. Unfortunately I couldn't reproduce it. My guess is that it is either the conda environment (for IJulia and co.) or atom's `apm` that couldn't go on without git. I'll have to fix it either way, since the installer must absolutely not have any external dependencies (and definitely not without warning).

**Comment by heetbeet** [comment]
@kuelshammer Juliawin now ensures that all downloads take place using curl. I never got to reproduce your error, but I'm certain that it's related to https://github.com/heetbeet/juliawin/issues/9

The script in the master branch now installs from a bare-bone W7 system, so I think it will probably not care for any possible git dependencies if it ever did.
